[package]
name = "shakthi_blinky"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shakti_riscv_hal = {path="../../"}
#panic-halt = "0.2.0"
riscv-rt = "0.13.0"
riscv = "0.12.1"
